export default strings = {
  //Login Up ============================
  LOGIN: "Login",
  LOGINMember: "Login As Member",
  LOGINMerchent: "Login As Merchent",
  RememberMe: "Remember Me",
  ForgotPassword: "Forgot Password",
  DontAccount: "Don't have account? ",
  PersonalDetail: "Enter Merchent Personal Detail",
  AddressDetail: "Enter Merchent Address Detail",
  EnterBusinessDetail: "Enter Merchent Business Detail",
  Continue: "Continue",
  SignUpMember: "Sign Up As Member",
  SignUpMerchent: "Sign Up As Merchent",
  ForgotPassword: "Forgot Password?",
  ResetPassword: "Please enter email address here.",
  ResetLink: "Sent Reset Password Link",
  PartnerUs: "Partner with Us",
  //Sign Up ============================
  Email: "Email",
  ConfirmEmail: "Confirm Email",
  FirstName: "First Name",
  LastName: "Last Name",
  Password: "Password",
  ConfirmPassword: "Confirm Password",
  Gender: "Gender",
  Category: "Category",
  SubCategory: "Sub Category",
  AddressLine1: "Address Line 1",
  AddressLine2: "Address Line 2",
  AddressLine3: "Address Line 3",
  City: "City",
  Country: "Country",
  PostCode: "Post Code",
  PhoneNumber: "Phone Number",
  Reffereal: "Refferal Code",
  BirthMonth: "Birth Month",
  AcceptText1: " I accept ",
  AcceptText2: " of Winngoo.",
  PrivacyPolicy: " Privacy Policy ",
  TermsCondition: "Terms and Conditions ",
  //change passowrd ============================
  changepassowrd: "Change Passoword",
  OldPassword: "Old Password",
  NewPassword: "New Password",
  ConfirmPassword: "Confirm Password",
  Update: "Update",
  Reset: "Reset",
  Create: "Create",
  //Profile ============================
  EditProfile: "Edit Profile",
  EditProfilePicture: "Edit Profile Picture",
  EditAddress: "Edit Address",
  PersonalInformation: "Personal Information",
  Name: "Name: ",
  Email: "Email: ",
  EmailStatus: "Email Verification Status: ",
  PhoneNumber: "Phone Number: ",
  DateOfBirth: "Date Of Birth: ",
  Address: "Address: ",
  //Add Card Detail ============================
  AddCardDetail: "Add Bank Detail",
  CardNumber: "Enter Account Number",
  CardName: "Enter Account Holder Name",
  BankName: "Enter Bank Name",
  SortNumber: "Enter Sort Number",
  RollNumber: "Building Society Roll Number",
  //Business  Information Detail ============================
  BusinessInformation: "Business Information",
  BusinessType: "Business Type: ",
  TradingName:"Trading Name: ",
  BusinessRelationship:"Business Relationship: ",
  BusinessDescription:"Business Description: ",
  YearsTrading:"Years of Trading: ",
  OwnerName:"Owner/Manager Name: ",
  RegistrationNumber:"Registration Number: ",
  Franchise:"Franchise: ",
  StartDate:"Start Date: ",
  ExpireDate:"Expire Date: ",
  //Wingo Card Detail ============================
  CardDetail: "Winngoo Bank Detail",
  //Business  Details ============================
  BusinessDetails: "Business Details",
  Category:"Category: ",
  SubCategory:"Sub Category: ",
  RewardValue:"Reward Value: ",
  RewardDetail:"Reward Detail: ",
  TermsConditions:"Terms and Conditions: ",
  Timing:"Timing",
  Monday:"Monday: ",
  Tuesday:"Tuesday: ",
  Wednesday:"Wednesday: ",
  Thursday:"Thursday: ",
  Friday:"Friday: ",
  Saturday:"Saturday: ",
  Sunday:"Sunday: ",
  //Refer a Freind ============================
  ReferFriends: "Refer Friends",
  text1: "It pays to have friends!",
  text2: "Refer Now!",
  text3: "Get 25% of Your Friends registration amount as referral bonus.",
  text4: "There is no upper limit on the number of friends you can refer and also no cap on the amount of referral bonus you can earn.",
  inviteGmail:"Invite By Gmail",
  OR:"OR",
  CopyLink:"Copy Link",
  //Referal Summary============================
  ReferSummary: "Manage Referral Summary",
  //News ============================
  News: "News",
  //Transaction Interface ============================
  TransactionInterface: "Transaction Interface",
  submit: "Submit",
  //Member News ============================
  MemberNews: "Member News",
  //Newsletter ============================
  Newsletter: "Newsletter",
  Note: "Note",
  Note2: "Get our weekly newsletter to receive news and updates about our discounts, vouchers, cashback, merchants, and more.",
  Note1: "Be the first one to get the best deals from your favourite merchants!",
  NoteText:"1.By subscribing, you are agreeing to our terms and conditions.\n2.You can unsubscribe at any time.\n3.For information about our privacy practices, please click here.",
  //Place holder ============================
  EnterEmail: "Enter email here",
  EnterConfirmEmail: "Enter confirm email here",
  EnterFname: "Enter first name here",
  EnterLname: "Enter last name here",
  EnterAddress1: "Enter address line 1 here",
  EnterAddress2: "Enter address line 2 here",
  EnterAddress3: "Enter address line 3 here",
  EnterPassword: "Enter password here",
  EnterConfirmPassword: "Enter confirm password here",
  EnterCity: "Enter city here",
  EnterCountry: "Enter country here",
  EnterBirthMonth: "Enter birth month here",
  EnterReferralCode: "Enter refferal code here",
  EnterPhoneNumber: "Enter phone number here",
  EnterPostCode: "Enter post code here",
  //Error =================================
  EnterEmailErr: "Please enter valid email",
  EnterPasswordErr: "Please enter valid password",
  EnterConfirmEmailErr: "Please enter valid confirm email",
  EnterMatchEmailErr: "Email and confirm email not match",
  EnterMatchPasswordErr: "Password and confirm password not match",
  EnterFnameErr: "Please enter first name",
  EnterLnameErr: "Please enter last name",
  EnterConfirmPasswordErr: "Please enter valid confirm password",
  EnterPhoneNumberErr: "Please enter phone number",
  EnterGenderErr: "Please enter gender",


  EnterAddress1Err: "Please enter address line 1",
  EnterCityErr: "Please enter city",
  EnterCountryErr: "Please enter country",
  EnterPostCodeErr: "Please enter post code",

  EnterAddress1: "Enter address line 1 here",
  EnterAddress2: "Enter address line 2 here",
  EnterAddress3: "Enter address line 3 here",
  EnterPassword: "Enter password here",
  EnterCity: "Enter city here",
  EnterCountry: "Enter country here",
  EnterBirthMonth: "Enter birth month here",
  EnterReferralCode: "Enter refferal code here",
  EnterPostCode: "Enter post code here",
  EnterregistrationNumber: "Enter Registration Number here",
  EnterbusinessDescription: "Enter Business Description here",
  EnterbusinessDetail: "Enter Business Detail here",
  EntertradingYear: "Enter Trading Business Year here",
  EnterwebsiteLink: "Enter Website Link here",
};
