export default strings = {
  LOGIN: 'Login',
  LOGINMember: 'Login As Member',
  LOGINMerchent: 'Login As Merchent',
  RememberMe: 'Remember Me',
  ForgotPassword: 'Forgot Password',
  DontAccount: "Don't have account? ",
  SignUp: 'Sign Up',
  SignUpMember: 'Sign Up As Member',
  SignUpMerchent: 'Sign Up As Merchent',
  ForgotPassword: 'Forgot Password?',
  ResetPassword: 'Please enter email address here.',
  ResetLink: 'Sent Reset Password Link',
  PartnerUs:"Partner with Us",
  //Sign Up ============================
  Email: 'Email',
  ConfirmEmail: 'Confirm Email',
  FirstName:"First Name",
  LastName:"Last Name",
  Password:"Password",
  ConfirmPassword:"Confirm Password",
  Gender:"Gender",
  AddressLine1:"Address Line 1",
  AddressLine2:"Address Line 2",
  AddressLine3:"Address Line 3",
  City:"City",
  Country:"Country",
  PostCode:"Post Code",
  PhoneNumber:"Phone Number",
  Reffereal:"Refferal Code",
  BirthMonth:"Birth Month",
  AcceptText1:" I accept ",
  AcceptText2:" of Winngoo.",
  PrivacyPolicy:" Privacy Policy ",
  TermsCondition:"Terms and Conditions ",
  //Place holder ============================
  EnterEmail: 'Enter email here',
  EnterConfirmEmail: 'Enter confirm email here',
  EnterFname: 'Enter first name here',
  EnterLname: 'Enter last name here',
  EnterAddress1: 'Enter address line 1 here',
  EnterAddress2: 'Enter address line 2 here',
  EnterAddress3: 'Enter address line 3 here',
  EnterPassword: 'Enter password here',
  EnterConfirmPassword: 'Enter confirm password here',
  EnterCity: 'Enter city here',
  EnterCountry: 'Enter country here',
  EnterBirthMonth: 'Enter birth month here',
  EnterReferralCode: 'Enter refferal code here',
  EnterPhoneNumber: 'Enter phone number here',
  EnterPostCode: 'Enter post code here',
};
